version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: cosmic-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: cosmic_coffeehouse
    volumes:
      - mongodb_data:/data/db
      - ./backend/scripts/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - cosmic-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: cosmic-backend
    restart: unless-stopped
    ports:
      - "3001:3001"
    environment:
      NODE_ENV: development
      MONGODB_URI: mongodb://admin:password@mongodb:27017/cosmic_coffeehouse?authSource=admin
      JWT_SECRET: your-super-secret-jwt-key-for-development
      PORT: 3001
    depends_on:
      - mongodb
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - cosmic-network
    command: npm run dev

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: cosmic-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      VITE_API_URL: http://localhost:3001
      VITE_APP_NAME: The Cosmic Coffeehouse
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - cosmic-network
    command: npm run dev

  prometheus:
    image: prom/prometheus:latest
    container_name: cosmic-prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    networks:
      - cosmic-network

  grafana:
    image: grafana/grafana:latest
    container_name: cosmic-grafana
    restart: unless-stopped
    ports:
      - "3002:3000"
    environment:
      GF_SECURITY_ADMIN_PASSWORD: admin
    volumes:
      - grafana_data:/var/lib/grafana
      - ./monitoring/grafana/dashboards:/etc/grafana/provisioning/dashboards
      - ./monitoring/grafana/datasources:/etc/grafana/provisioning/datasources
    depends_on:
      - prometheus
    networks:
      - cosmic-network

volumes:
  mongodb_data:
  prometheus_data:
  grafana_data:

networks:
  cosmic-network:
    driver: bridge